### ISSUE TITLE
No gulpfile found

### ISSUE THREAD

**Issue by josealencar** [arsouza/ng-todo#1]
Seguindo os passos do README.md para instalação da aplicação, ao rodar o comando do gulp é encontrado o seguinte erro:
$ gulp
[09:14:53] No gulpfile found

Olhando nos históricos de commit vi que no commit 8d526655eb17b1b8470bcbe217b21c5c417c85c2 de  11 Dec 2015 foi removido o arquivo do gulp.
Tem uma outra forma de rodar a aplicação onde não seja necessário esse arquivo?

**Comment by arsouza** [comment]
O gulp foi removido do projeto e substituído pelo grunt (considere o inverso no futuro). O readme foi atualizado.
